export const payments = [
    {
        fecha: '1/02/2022',
        titulo: 'tarjeta',
        operacion: 'recarga',
        equipo: 'nodo',
        referencia: '1234',
        monto: '20',
        active: 'aprobado',
    },
    {
        fecha: '2/02/2022',
        titulo: 'tarjeta',
        operacion: 'recarga',
        equipo: 'nodo',
        referencia: '4567',
        monto: '10',
        active: 'denegado',
    },
    {
        fecha: '3/02/2022',
        titulo: 'tarjeta',
        operacion: 'recarga',
        equipo: 'nodo',
        referencia: '8912',
        monto: '5',
        active: 'denegado',
    },
    {
        fecha: '4/02/2022',
        titulo: 'tarjeta',
        operacion: 'recarga',
        equipo: 'nodo',
        referencia: '3456',
        monto: '30',
        active: 'aprobado',
    },
    {
        fecha: '5/02/2022',
        titulo: 'tarjeta',
        operacion: 'recarga',
        equipo: 'nodo',
        referencia: '7891',
        monto: '10',
        active: 'aprobado',
    },
    {
        fecha: '6/02/2022',
        titulo: 'tarjeta',
        operacion: 'recarga',
        equipo: 'nodo',
        referencia: '5897',
        monto: '18',
        active: 'denegado',
    },
]
